CREATE TABLE [dbo].[MEMBER_EMAIL]
(
	[MEMBER_EMAIL_ID]	INT IDENTITY NOT NULL 
		CONSTRAINT MEMBER_EMAIL_PK PRIMARY KEY CLUSTERED
,	[MEMBER_ID]			INT NOT NULL
		CONSTRAINT MEMBER_EMAIL_MEMBER_FK 
			FOREIGN KEY REFERENCES dbo.MEMBER (MEMBER_ID)
,	[EMAIL_TYPE]		VARCHAR(10) NOT NULL
,	[EMAIL_ADDRESS]		VARCHAR(50) NOT NULL
)
